// <auto-generated />
using System;
using Dobu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Dobu.Infrastructure.Migrations
{
    [DbContext(typeof(DobuDbContext))]
    partial class DobuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dobu.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_AGENDAMENTO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AGENDAMENTO");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS_AGENDAMENTO");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VETERINARIO_FK");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("AGENDAMENTO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.AnaliseIa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ANALISE_IA_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ANALISE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("NVARCHAR2(800)")
                        .HasColumnName("DESC_ANALISE");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PRONTUARIO_FK");

                    b.Property<int>("Risco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_RISCO");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId")
                        .IsUnique();

                    b.ToTable("ANALISE_IA", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CONSULTA_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSULTA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC_CONSULTA");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR_CONSULTA");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VETERINARIO_FK");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("CONSULTA", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.DobuCam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_DOBUCAM_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("DataUltimaMovimentacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ULTIMA_MOVIMENTACAO");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DESC_LOCALIZACAO");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.Property<string>("StatusCamera")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS_CAMERA");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("DOBUCAM", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ESPECIE_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESC_ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_ESPECIE");

                    b.HasKey("Id");

                    b.ToTable("ESPECIE", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.InformacaoCuidado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_INFORMACAO_CUIDADO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("INFORMACAO_CUIDADO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Lembrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_LEMBRETE_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataLembrete")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEMBRETE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESC_LEMBRETE");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS_LEMBRETE");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("LEMBRETE", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.LogErro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_LOG_ERRO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataErro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ERRO");

                    b.Property<string>("DescricaoErro")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESC_ERRO");

                    b.Property<string>("NomeProcedure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PROCEDURE");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO_FK");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LOG_ERRO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PAGAMENTO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CONSULTA_FK");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PAGAMENTO");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("TIPO_FORMA_PAGAMENTO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR_PAGAMENTO");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("Idade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_PET");

                    b.Property<Guid>("RacaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_RACA_FK");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_RESPONSAVEL_FK");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PRONTUARIO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CONSULTA_FK");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC_DIAGNOSTICO");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC_OBSERVACOES");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("PRONTUARIO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_RACA_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Cuidados")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC_CUIDADOS");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESC_RACA");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ESPECIE_FK");

                    b.Property<int>("ExpectativaVida")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_EXPECTATIVA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_RACA");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_PORTE");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DESC_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESC_SENHA");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Vacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VACINA_PK");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_APLICACAO");

                    b.Property<DateTime?>("DataProximaDose")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PROXIMA_DOSE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_VACINA");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET_FK");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("VACINA", (string)null);
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dobu.Domain.Entities.Usuario", "Veterinario")
                        .WithMany("AgendamentosVeterinario")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.AnaliseIa", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Prontuario", "Prontuario")
                        .WithOne("AnaliseIa")
                        .HasForeignKey("Dobu.Domain.Entities.AnaliseIa", "ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dobu.Domain.Entities.Usuario", "Veterinario")
                        .WithMany("ConsultasVeterinario")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.DobuCam", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("DobuCams")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.InformacaoCuidado", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("InformacoesCuidado")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("Lembretes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.LogErro", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsErro")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Consulta", "Consulta")
                        .WithOne("Pagamento")
                        .HasForeignKey("Dobu.Domain.Entities.Pagamento", "ConsultaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Pet", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Raca", "Raca")
                        .WithMany("Pets")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dobu.Domain.Entities.Usuario", "Responsavel")
                        .WithMany("PetsResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Consulta", "Consulta")
                        .WithOne("Prontuario")
                        .HasForeignKey("Dobu.Domain.Entities.Prontuario", "ConsultaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Raca", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Vacina", b =>
                {
                    b.HasOne("Dobu.Domain.Entities.Pet", "Pet")
                        .WithMany("Vacinas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("Pagamento");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Consultas");

                    b.Navigation("DobuCams");

                    b.Navigation("InformacoesCuidado");

                    b.Navigation("Lembretes");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("AnaliseIa");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Dobu.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AgendamentosVeterinario");

                    b.Navigation("ConsultasVeterinario");

                    b.Navigation("LogsErro");

                    b.Navigation("PetsResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
