<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Dobu.Application</AssemblyName>
        <RootNamespace>Dobu.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dobu.Domain\Dobu.Domain.csproj" />
    </ItemGroup>

</Project>
